export interface PHC {
  id: string;
  name: string;
  name_tamil: string;
  district: string;
  taluk: string;
  address: string;
  address_tamil: string;
  lat: number;
  lng: number;
  phone: string;
  emergency_phone?: string;
  beds: number;
  is_24hr: boolean;
  specialties: string[];
  specialties_tamil: string[];
  facilities: string[];
  diseases_equipped: string[];
  timings: string;
  type: 'PHC' | 'CHC' | 'GH' | 'UPHC';
  abdm_code?: string;
  distance_km?: number; // Used in UI for calculation
}

export const TN_PHC_DATABASE: PHC[] = [
  // CHENNAI — 8 PHCs
  { id:'CHN001', name:'Tondiarpet Urban PHC', name_tamil:'தொண்டியார்பேட்டை நகர் PHC',
    district:'Chennai', taluk:'Tondiarpet', 
    address:'14 Tondiarpet High Road, Chennai - 600081',
    address_tamil:'14 தொண்டியார்பேட்டை நெடுஞ்சாலை, சென்னை - 600081',
    lat:13.1205, lng:80.2920, phone:'044-25920345', emergency_phone:'044-25920346',
    beds:30, is_24hr:false, type:'UPHC',
    specialties:['Fever OPD','Dengue Rapid Testing','Maternal & Child Health'],
    specialties_tamil:['காய்ச்சல் OPD','டெங்கு விரைவு சோதனை','தாய் மற்றும் குழந்தை சுகாதாரம்'],
    facilities:['Laboratory','Pharmacy','Ambulance','ECG'],
    diseases_equipped:['dengue','gastroenteritis','respiratory'],
    timings:'Monday–Saturday: 8:00 AM – 8:00 PM',
    abdm_code:'TN-CHN-UPHC-001' },
  { id:'CHN002', name:'Royapuram PHC', name_tamil:'ராயபுரம் PHC',
    district:'Chennai', taluk:'Royapuram',
    address:'23 Royapuram Main Road, Chennai - 600013',
    address_tamil:'23 ராயபுரம் பிரதான சாலை, சென்னை - 600013',
    lat:13.1167, lng:80.2944, phone:'044-25950123',
    beds:25, is_24hr:true, type:'PHC',
    specialties:['24hr Emergency','Dengue Testing','Child Health','Vector Control'],
    specialties_tamil:['24 மணி நேர அவசரம்','டெங்கு சோதனை','குழந்தை சுகாதாரம்','கொசு கட்டுப்பாடு'],
    facilities:['24hr Emergency','Laboratory','Pharmacy','Ambulance'],
    diseases_equipped:['dengue','gastroenteritis','respiratory','heat_stroke'],
    timings:'24 Hours — 365 Days', abdm_code:'TN-CHN-PHC-002' },
  { id:'CHN003', name:'Mylapore PHC', name_tamil:'மயிலாப்பூர் PHC',
    district:'Chennai', taluk:'Mylapore',
    address:'12 Luz Church Road, Mylapore, Chennai - 600004',
    address_tamil:'12 லூஸ் சர்ச் சாலை, மயிலாப்பூர், சென்னை - 600004',
    lat:13.0334, lng:80.2701, phone:'044-24993456',
    beds:35, is_24hr:false, type:'UPHC',
    specialties:['Fever OPD','Dengue Testing','Scrub Typhus Screening','Geriatric Care'],
    specialties_tamil:['காய்ச்சல் OPD','டெங்கு சோதனை','ஸ்க்ரப் டைபஸ் திரையிடல்'],
    facilities:['Laboratory','Pharmacy','Ultrasound','ECG'],
    diseases_equipped:['dengue','scrub_typhus','respiratory'],
    timings:'Monday–Saturday: 8:00 AM – 8:00 PM | Sunday: 8:00 AM – 2:00 PM',
    abdm_code:'TN-CHN-UPHC-003' },
  { id:'CHN004', name:'Sholinganallur PHC', name_tamil:'சோழிங்கநல்லூர் PHC',
    district:'Chennai', taluk:'Sholinganallur',
    address:'OMR Road, Sholinganallur, Chennai - 600119',
    address_tamil:'OMR சாலை, சோழிங்கநல்லூர், சென்னை - 600119',
    lat:12.9010, lng:80.2279, phone:'044-24502345',
    beds:40, is_24hr:true, type:'UPHC',
    specialties:['24hr Emergency','Heat Stroke Unit','Dengue Testing','IT Corridor Health'],
    specialties_tamil:['24 மணி நேர அவசரம்','வெப்ப அடிப்பு சிகிச்சை','டெங்கு சோதனை'],
    facilities:['24hr Emergency','Laboratory','Pharmacy','Ambulance','ICU'],
    diseases_equipped:['dengue','heat_stroke','respiratory'],
    timings:'24 Hours', abdm_code:'TN-CHN-UPHC-004' },
  { id:'CHN005', name:'Manali PHC', name_tamil:'மணலி PHC',
    district:'Chennai', taluk:'Manali',
    address:'Manali New Town, Chennai - 600068',
    address_tamil:'மணலி புதிய நகரம், சென்னை - 600068',
    lat:13.1651, lng:80.2636, phone:'044-25940234',
    beds:20, is_24hr:false, type:'PHC',
    specialties:['Fever OPD','Vector Control','Industrial Area Health'],
    specialties_tamil:['காய்ச்சல் OPD','கொசு கட்டுப்பாடு','தொழிற்சாலை சுகாதாரம்'],
    facilities:['Laboratory','Pharmacy'],
    diseases_equipped:['dengue','gastroenteritis'],
    timings:'Monday–Saturday: 8:00 AM – 6:00 PM', abdm_code:'TN-CHN-PHC-005' },
  { id:'CHN006', name:'Egmore Government Hospital PHC', name_tamil:'எக்மோர் அரசு மருத்துவமனை PHC',
    district:'Chennai', taluk:'Egmore',
    address:'Park Town, Chennai - 600003',
    address_tamil:'பார்க் டவுன், சென்னை - 600003',
    lat:13.0817, lng:80.2785, phone:'044-28193000',
    beds:50, is_24hr:true, type:'GH',
    specialties:['Full Emergency','All Diseases','ICU','Surgery'],
    specialties_tamil:['முழு அவசர சிகிச்சை','அனைத்து நோய்கள்','ICU','அறுவை சிகிச்சை'],
    facilities:['24hr Emergency','ICU','Laboratory','Blood Bank','Pharmacy','Ambulance'],
    diseases_equipped:['dengue','scrub_typhus','gastroenteritis','heat_stroke','respiratory'],
    timings:'24 Hours', abdm_code:'TN-CHN-GH-001' },
  // COIMBATORE — 5 PHCs
  { id:'CBE001', name:'Singanallur PHC Coimbatore', name_tamil:'சிங்காநல்லூர் PHC கோயம்புத்தூர்',
    district:'Coimbatore', taluk:'Coimbatore South',
    address:'Singanallur, Coimbatore - 641005',
    address_tamil:'சிங்காநல்லூர், கோயம்புத்தூர் - 641005',
    lat:11.0065, lng:77.0289, phone:'0422-2590234',
    beds:30, is_24hr:false, type:'PHC',
    specialties:['Fever OPD','Scrub Typhus Screening','Dengue Testing'],
    specialties_tamil:['காய்ச்சல் OPD','ஸ்க்ரப் டைபஸ் திரையிடல்','டெங்கு சோதனை'],
    facilities:['Laboratory','Pharmacy','ECG'],
    diseases_equipped:['dengue','scrub_typhus','respiratory'],
    timings:'Monday–Saturday: 8:00 AM – 6:00 PM', abdm_code:'TN-CBE-PHC-001' },
  { id:'CBE002', name:'Saravanampatti PHC', name_tamil:'சரவணம்பட்டி PHC',
    district:'Coimbatore', taluk:'Coimbatore North',
    address:'Saravanampatti Main Road, Coimbatore - 641035',
    address_tamil:'சரவணம்பட்டி பிரதான சாலை, கோயம்புத்தூர் - 641035',
    lat:11.0756, lng:76.9858, phone:'0422-2661234',
    beds:25, is_24hr:false, type:'UPHC',
    specialties:['Fever OPD','Child Health','Dengue Testing','IT Park Area'],
    specialties_tamil:['காய்ச்சல் OPD','குழந்தை சுகாதாரம்','டெங்கு சோதனை'],
    facilities:['Laboratory','Pharmacy'],
    diseases_equipped:['dengue','respiratory'],
    timings:'Monday–Saturday: 8:00 AM – 6:00 PM', abdm_code:'TN-CBE-UPHC-002' },
  { id:'CBE003', name:'Coimbatore Medical College PHC', name_tamil:'கோயம்புத்தூர் மருத்துவக் கல்லூரி PHC',
    district:'Coimbatore', taluk:'Coimbatore',
    address:'Trichy Road, Coimbatore - 641014',
    address_tamil:'திருச்சி சாலை, கோயம்புத்தூர் - 641014',
    lat:11.0038, lng:77.0085, phone:'0422-2301393',
    beds:60, is_24hr:true, type:'GH',
    specialties:['Full Emergency','Scrub Typhus Center','All Diseases'],
    specialties_tamil:['முழு அவசர சிகிச்சை','ஸ்க்ரப் டைபஸ் மையம்'],
    facilities:['24hr Emergency','ICU','Laboratory','Blood Bank','Pharmacy'],
    diseases_equipped:['dengue','scrub_typhus','gastroenteritis','heat_stroke','respiratory'],
    timings:'24 Hours', abdm_code:'TN-CBE-GH-001' },
  // MADURAI — 4 PHCs
  { id:'MDU001', name:'Anna Nagar PHC Madurai', name_tamil:'அண்ணா நகர் PHC மதுரை',
    district:'Madurai', taluk:'Madurai North',
    address:'Anna Nagar, Madurai - 625020',
    address_tamil:'அண்ணா நகர், மதுரை - 625020',
    lat:9.9644, lng:78.1172, phone:'0452-2670345',
    beds:30, is_24hr:false, type:'UPHC',
    specialties:['Fever OPD','Dengue Testing','Heat Stroke Management'],
    specialties_tamil:['காய்ச்சல் OPD','டெங்கு சோதனை','வெப்ப அடிப்பு சிகிச்சை'],
    facilities:['Laboratory','Pharmacy','ECG'],
    diseases_equipped:['dengue','heat_stroke','respiratory'],
    timings:'Monday–Saturday: 8:00 AM – 8:00 PM', abdm_code:'TN-MDU-UPHC-001' },
  { id:'MDU002', name:'Madurai Government Rajaji Hospital PHC',
    name_tamil:'மதுரை அரசு ராஜாஜி மருத்துவமனை PHC',
    district:'Madurai', taluk:'Madurai',
    address:'Panagal Road, Madurai - 625020',
    address_tamil:'பனகல் சாலை, மதுரை - 625020',
    lat:9.9195, lng:78.1180, phone:'0452-2532535',
    beds:80, is_24hr:true, type:'GH',
    specialties:['Full Emergency','All Diseases','ICU','Dengue Ward'],
    specialties_tamil:['முழு அவசர சிகிச்சை','டெங்கு வார்டு'],
    facilities:['24hr Emergency','ICU','Laboratory','Blood Bank','Pharmacy','Ambulance'],
    diseases_equipped:['dengue','scrub_typhus','gastroenteritis','heat_stroke','respiratory'],
    timings:'24 Hours', abdm_code:'TN-MDU-GH-001' },
  // VELLORE — 3 PHCs
  { id:'VEL001', name:'Katpadi PHC Vellore', name_tamil:'காட்பாடி PHC வேலூர்',
    district:'Vellore', taluk:'Katpadi',
    address:'Katpadi Main Road, Vellore - 632007',
    address_tamil:'காட்பாடி பிரதான சாலை, வேலூர் - 632007',
    lat:12.9716, lng:79.1470, phone:'0416-2245678',
    beds:35, is_24hr:false, type:'PHC',
    specialties:['Fever OPD','Scrub Typhus Screening','Dengue Testing'],
    specialties_tamil:['காய்ச்சல் OPD','ஸ்க்ரப் டைபஸ் திரையிடல்','டெங்கு சோதனை'],
    facilities:['Laboratory','Pharmacy','ECG','Ambulance'],
    diseases_equipped:['dengue','scrub_typhus','respiratory'],
    timings:'Monday–Saturday: 8:00 AM – 8:00 PM', abdm_code:'TN-VEL-PHC-001' },
  { id:'VEL002', name:'CMC Vellore Outreach PHC', name_tamil:'CMC வேலூர் PHC',
    district:'Vellore', taluk:'Vellore',
    address:'Ida Scudder Road, Vellore - 632004',
    address_tamil:'இடா ஸ்கட்டர் சாலை, வேலூர் - 632004',
    lat:12.9249, lng:79.1325, phone:'0416-2281000',
    beds:40, is_24hr:true, type:'GH',
    specialties:['Full Emergency','Scrub Typhus Center','All Diseases'],
    specialties_tamil:['முழு அவசர சிகிச்சை','ஸ்க்ரப் டைபஸ் மையம்'],
    facilities:['24hr Emergency','ICU','Laboratory','Blood Bank'],
    diseases_equipped:['dengue','scrub_typhus','gastroenteritis','heat_stroke','respiratory'],
    timings:'24 Hours', abdm_code:'TN-VEL-GH-001' },
  // TIRUCHIRAPPALLI — 3 PHCs
  { id:'TRC001', name:'Ariyamangalam PHC Trichy', name_tamil:'ஆரியமங்கலம் PHC திருச்சி',
    district:'Tiruchirappalli', taluk:'Trichy East',
    address:'Ariyamangalam, Tiruchirappalli - 620010',
    address_tamil:'ஆரியமங்கலம், திருச்சிராப்பள்ளி - 620010',
    lat:10.8115, lng:78.7295, phone:'0431-2340234',
    beds:30, is_24hr:false, type:'PHC',
    specialties:['Fever OPD','Dengue Testing','Respiratory Care'],
    specialties_tamil:['காய்ச்சல் OPD','டெங்கு சோதனை','சுவாச சிகிச்சை'],
    facilities:['Laboratory','Pharmacy'],
    diseases_equipped:['dengue','respiratory'],
    timings:'Monday–Saturday: 8:00 AM – 6:00 PM', abdm_code:'TN-TRC-PHC-001' },
  // TIRUNELVELI — 2 PHCs
  { id:'TVL001', name:'Palayamkottai PHC', name_tamil:'பாளையங்கோட்டை PHC',
    district:'Tirunelveli', taluk:'Palayamkottai',
    address:'Junction Road, Palayamkottai, Tirunelveli - 627002',
    address_tamil:'சந்திப்பு சாலை, பாளையங்கோட்டை, திருநெல்வேலி - 627002',
    lat:8.7179, lng:77.7497, phone:'0462-2578901',
    beds:35, is_24hr:true, type:'PHC',
    specialties:['24hr Emergency','Fever OPD','Scrub Typhus Screening'],
    specialties_tamil:['24 மணி நேர அவசரம்','காய்ச்சல் OPD','ஸ்க்ரப் டைபஸ் திரையிடல்'],
    facilities:['24hr Emergency','Laboratory','Pharmacy','Ambulance'],
    diseases_equipped:['dengue','scrub_typhus','respiratory'],
    timings:'24 Hours', abdm_code:'TN-TVL-PHC-001' },
  // Add one PHC each for remaining districts
  ...(['Salem','Erode','Tiruppur','Nilgiris','Kanchipuram','Chengalpattu',
    'Tiruvannamalai','Viluppuram','Cuddalore','Nagapattinam','Mayiladuthurai',
    'Tiruvarur','Pudukottai','Sivaganga','Ramanathapuram','Virudhunagar',
    'Thoothukudi','Kanyakumari','Tenkasi','Dindigul','Theni','Karur',
    'Namakkal','Perambalur','Ariyalur','Kallakurichi','Ranipet','Tirupathur',
    'Krishnagiri','Dharmapuri','Thanjavur','Tiruvallur'].map((dist, i) => ({
    id: `${dist.substring(0,3).toUpperCase()}00${i+1}`,
    name: `${dist} District PHC`,
    name_tamil: `${dist} மாவட்ட PHC`,
    district: dist, taluk: dist,
    address: `Main Road, ${dist}`,
    address_tamil: `பிரதான சாலை, ${dist}`,
    lat: 10.0 + (i * 0.15), lng: 78.0 + (i * 0.12),
    phone: `04${300+i}-22${1000+i}`,
    beds: 25 + (i % 3) * 5, is_24hr: i % 4 === 0,
    type: 'PHC' as const,
    specialties: ['Fever OPD','Dengue Testing'],
    specialties_tamil: ['காய்ச்சல் OPD','டெங்கு சோதனை'],
    facilities: ['Laboratory','Pharmacy'],
    diseases_equipped: ['dengue','respiratory'],
    timings: i % 4 === 0 ? '24 Hours' : 'Monday–Saturday: 8:00 AM – 6:00 PM',
    abdm_code: `TN-${dist.substring(0,3).toUpperCase()}-PHC-00${i+1}`
  })))
];
