import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { emailType, alertId, disease, ward, affected, targetEmails } = body;

    const senderEmail = process.env.GMAIL_SENDER_EMAIL;
    const appPassword = process.env.GMAIL_APP_PASSWORD;

    if (!senderEmail || !appPassword) {
      return NextResponse.json(
        { error: 'Email credentials not configured in environment variables' },
        { status: 500 }
      );
    }

    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: senderEmail,
        pass: appPassword,
      },
    });

    let subject = '';
    let text = '';
    let html = '';

    if (emailType === 'OFFICIAL') {
      subject = `CRITICAL ALERT: ${disease} Surge Detected - ${ward}`;
      text = `Nalam AI Alert System\n\nDisease: ${disease}\nWard: ${ward}\nPopulation at Risk: ${affected}\n\nAction Required: Mobilize vector control teams, initiate medicine indents for paracetamol and IV fluids. View dashboard for precise geo-locations.`;
      html = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
          <div style="background-color: #0f172a; padding: 20px; text-align: center; border-bottom: 4px solid #f59e0b;">
            <h1 style="color: white; margin: 0;">Nalam AI Command Center</h1>
            <p style="color: #cbd5e1; margin-top: 5px; font-size: 14px;">Official Health Surveillance Alert</p>
          </div>
          <div style="padding: 30px; background-color: #f8fafc;">
            <h2 style="color: #dc2626; margin-top: 0;">CRITICAL: ${disease} Surge Detected</h2>
            <p><strong>District/Ward:</strong> ${ward}</p>
            <p><strong>Population at Risk:</strong> ${affected.toLocaleString()}</p>
            <p><strong>Alert ID:</strong> #${alertId}</p>
            <div style="background-color: #fef2f2; border-left: 4px solid #dc2626; padding: 15px; margin-top: 20px;">
              <h3 style="color: #991b1b; margin-top: 0; font-size: 16px;">Recommended Action Plan</h3>
              <ul style="color: #7f1d1d; margin-bottom: 0; padding-left: 20px;">
                <li>Mobilize vector control teams immediately in the affected zones.</li>
                <li>Initiate emergency medicine indents (Paracetamol, IV Fluids) at local PHCs.</li>
                <li>Access the <a href="http://localhost:3000/admin" style="color: #2563eb; font-weight: bold;">Nalam AI Dashboard</a> for real-time ward maps and predictive resource calculations.</li>
              </ul>
            </div>
          </div>
          <div style="background-color: #f1f5f9; padding: 15px; text-align: center; font-size: 12px; color: #64748b;">
            <p>This is an automated alert generated by the Government of Tamil Nadu's AI Surveillance System.</p>
          </div>
        </div>
      `;
    }

    const mailOptions = {
      from: `"Nalam AI Command Center" <${senderEmail}>`,
      to: targetEmails.join(', '),
      subject,
      text,
      html,
    };

    const info = await transporter.sendMail(mailOptions);

    return NextResponse.json({ success: true, messageId: info.messageId });
  } catch (error: any) {
    console.error('Email dispatch error:', error);
    return NextResponse.json(
      { error: 'Failed to send email', details: error.message },
      { status: 500 }
    );
  }
}
